// Copyright 2026 ananth-menon. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package mcp

import (
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	mcplib "github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"
	"github.com/ananthmenon10/livefpl/internal/cli"
	"github.com/ananthmenon10/livefpl/internal/client"
	"github.com/ananthmenon10/livefpl/internal/cliutil"
	"github.com/ananthmenon10/livefpl/internal/config"
	"github.com/ananthmenon10/livefpl/internal/mcp/cobratree"
	"github.com/ananthmenon10/livefpl/internal/store"
)

// RegisterTools registers all API operations as MCP tools.
func RegisterTools(s *server.MCPServer) {
	s.AddTool(
		mcplib.NewTool("bootstrap-static_get",
			mcplib.WithDescription("~1.5MB. The single most important read in the FPL API. Loaded once and cached locally for all entity lookups."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/bootstrap-static/", false, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("dream-team_get",
			mcplib.WithDescription("Highest-scoring XI for a gameweek. Required: eventId."),
			mcplib.WithNumber("eventId", mcplib.Required(), mcplib.Description("Event id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/dream-team/{eventId}/", false, []mcpParamBinding{{PublicName: "eventId", WireName: "eventId", Location: "path"}}, []string{"eventId"}),
	)
	s.AddTool(
		mcplib.NewTool("element-summary_get",
			mcplib.WithDescription("Per-player detail (history + upcoming fixtures). Required: elementId."),
			mcplib.WithNumber("elementId", mcplib.Required(), mcplib.Description("Element id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/element-summary/{elementId}/", false, []mcpParamBinding{{PublicName: "elementId", WireName: "elementId", Location: "path"}}, []string{"elementId"}),
	)
	s.AddTool(
		mcplib.NewTool("elite-json_get-elite-aggregates",
			mcplib.WithDescription("Aggregated picks, captaincy %, ownership, and chip usage among the top 10,000 ranked managers. ~10KB, refreshed each gameweek."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "https://livefpl.us/elite.json", false, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("entry_get",
			mcplib.WithDescription("Manager profile (name, country, leagues, summary score). Required: managerId."),
			mcplib.WithNumber("managerId", mcplib.Required(), mcplib.Description("Manager id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/entry/{managerId}/", false, []mcpParamBinding{{PublicName: "managerId", WireName: "managerId", Location: "path"}}, []string{"managerId"}),
	)
	s.AddTool(
		mcplib.NewTool("entry_event_get-entry-picks",
			mcplib.WithDescription("Manager picks for a specific gameweek. Required: managerId, eventId."),
			mcplib.WithNumber("managerId", mcplib.Required(), mcplib.Description("Manager id")),
			mcplib.WithNumber("eventId", mcplib.Required(), mcplib.Description("Event id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/entry/{managerId}/event/{eventId}/picks/", false, []mcpParamBinding{{PublicName: "managerId", WireName: "managerId", Location: "path"}, {PublicName: "eventId", WireName: "eventId", Location: "path"}}, []string{"managerId", "eventId"}),
	)
	s.AddTool(
		mcplib.NewTool("entry_history_get-entry",
			mcplib.WithDescription("Manager history (per-GW score, past seasons, chips). Required: managerId."),
			mcplib.WithNumber("managerId", mcplib.Required(), mcplib.Description("Manager id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/entry/{managerId}/history/", false, []mcpParamBinding{{PublicName: "managerId", WireName: "managerId", Location: "path"}}, []string{"managerId"}),
	)
	s.AddTool(
		mcplib.NewTool("entry_transfers_get-entry",
			mcplib.WithDescription("Manager transfers (all transfers this season). Required: managerId."),
			mcplib.WithNumber("managerId", mcplib.Required(), mcplib.Description("Manager id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/entry/{managerId}/transfers/", false, []mcpParamBinding{{PublicName: "managerId", WireName: "managerId", Location: "path"}}, []string{"managerId"}),
	)
	s.AddTool(
		mcplib.NewTool("event_live_get-event",
			mcplib.WithDescription("Live gameweek stats (per-player points and explain breakdown). Required: eventId."),
			mcplib.WithNumber("eventId", mcplib.Required(), mcplib.Description("Event id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/event/{eventId}/live/", false, []mcpParamBinding{{PublicName: "eventId", WireName: "eventId", Location: "path"}}, []string{"eventId"}),
	)
	s.AddTool(
		mcplib.NewTool("event-status_get",
			mcplib.WithDescription("Bonus and league update status across active GW."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/event-status/", false, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("fixtures_get",
			mcplib.WithDescription("All season fixtures (optionally filtered by event). Optional: event, future."),
			mcplib.WithNumber("event", mcplib.Description("Event")),
			mcplib.WithNumber("future", mcplib.Description("Future")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/fixtures/", false, []mcpParamBinding{{PublicName: "event", WireName: "event", Location: "query"}, {PublicName: "future", WireName: "future", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("games-json_get-live-games",
			mcplib.WithDescription("Array of arrays — one per Premier League fixture in the active gameweek. Each entry: [home, away, hscore, ascore, status, source, h_scorers, h_assists, a_scorers, a_assists, bps_top, ..., per-player live entries with BPS, minutes, clean sheets, bonus]. Update frequency: ~1-2 min during live matches. Optional: _."),
			mcplib.WithString("_", mcplib.Description("Cache-busting epoch timestamp")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "https://livefpl.us/api/games.json", false, []mcpParamBinding{{PublicName: "_", WireName: "_", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("leagues-classic_standings_get-classic-league",
			mcplib.WithDescription("Classic league standings (paginated). Required: leagueId. Optional: page_standings, page_new_entries."),
			mcplib.WithNumber("leagueId", mcplib.Required(), mcplib.Description("League id")),
			mcplib.WithNumber("page_standings", mcplib.Description("Page standings")),
			mcplib.WithNumber("page_new_entries", mcplib.Description("Page new entries")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/leagues-classic/{leagueId}/standings/", false, []mcpParamBinding{{PublicName: "leagueId", WireName: "leagueId", Location: "path"}, {PublicName: "page_standings", WireName: "page_standings", Location: "query"}, {PublicName: "page_new_entries", WireName: "page_new_entries", Location: "query"}}, []string{"leagueId"}),
	)
	s.AddTool(
		mcplib.NewTool("leagues-h2h-matches_get-h2h-league-matches",
			mcplib.WithDescription("H2H league matches. Required: leagueId."),
			mcplib.WithNumber("leagueId", mcplib.Required(), mcplib.Description("League id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/leagues-h2h-matches/league/{leagueId}/", false, []mcpParamBinding{{PublicName: "leagueId", WireName: "leagueId", Location: "path"}}, []string{"leagueId"}),
	)
	s.AddTool(
		mcplib.NewTool("lh-api2_get-planner-snapshot",
			mcplib.WithDescription("Returns FT, bank, chips_available, base_gw, eleven, picks, benches, bought_values per element_id, manager_name, original picks (start of GW), epicks (effective picks after auto-subs). Used by LiveFPL's transfer planner UI. Required: id."),
			mcplib.WithNumber("id", mcplib.Required(), mcplib.Description("Id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "https://livefpl-api-489391001748.europe-west4.run.app/LH_api2/planner/snapshot", false, []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("livefplapi_get-live-team",
			mcplib.WithDescription("THE primary LiveFPL transcendence endpoint. Returns: - GWrank: current gameweek rank - GWrank2: projected/secondary rank - a_e / a_o / a_t: average scores (entry/overall/top tiers) - arrow_*: visual rank-direction indicators - avg_similarity: how template the team is - bench, benchzz: bench points + bench element_ids - buds: similar-manager comparisons - cache: cache key - calcplayerptsd: live calculated points per element_id - and ~40 more fields Single endpoint per team; ~80KB. Public, no auth. Required: teamId."),
			mcplib.WithNumber("teamId", mcplib.Required(), mcplib.Description("Team id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "https://www.livefpl.net/livefplapi/{teamId}", false, []mcpParamBinding{{PublicName: "teamId", WireName: "teamId", Location: "path"}}, []string{"teamId"}),
	)
	s.AddTool(
		mcplib.NewTool("locals-league-id-json_get-league-locals-snapshot",
			mcplib.WithDescription("Available for indexed (popular) leagues; small leagues 404 here and must use the dynamic livefplapi path on www.livefpl.net. Required: leagueId."),
			mcplib.WithNumber("leagueId", mcplib.Required(), mcplib.Description("League id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "https://livefpl.us/locals_{leagueId}.json", false, []mcpParamBinding{{PublicName: "leagueId", WireName: "leagueId", Location: "path"}}, []string{"leagueId"}),
	)
	s.AddTool(
		mcplib.NewTool("me_get",
			mcplib.WithDescription("Authenticated user's own profile. (requires API key)"),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/me/", false, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("my-team_get",
			mcplib.WithDescription("Requires a session cookie from a logged-in fantasy.premierleague.com session. Opt-in only; we surface this behind a `--with-auth` flag and an env var (PP_FPL_SESSION_COOKIE) so accidental agent loops cannot trigger it. Required: managerId. (requires API key)"),
			mcplib.WithNumber("managerId", mcplib.Required(), mcplib.Description("Manager id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/my-team/{managerId}/", false, []mcpParamBinding{{PublicName: "managerId", WireName: "managerId", Location: "path"}}, []string{"managerId"}),
	)
	s.AddTool(
		mcplib.NewTool("prices-json_get-prices",
			mcplib.WithDescription("Dict keyed by FPL element_id. Each value: {name, team, type (GK/DEF/MID/FWD), type_code, team_code, cost, progress, progress_tonight, per_hour}. Used by LiveFPL's price-change predictor."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "https://livefpl.us/api/prices.json", false, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("team_get-set-piece-notes",
			mcplib.WithDescription("Set-piece taker notes per club."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/team/set-piece-notes/", false, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("top-transfers-json_get-top-transfers",
			mcplib.WithDescription("Array of [out_player_id, in_player_id, count_million, pct_share]. Sorted descending by volume. Updated every few minutes during transfer windows."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "https://livefpl.us/top_transfers.json", false, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("version-json_get-version",
			mcplib.WithDescription("Returns {gen, version, meter, store, league}. `gen` increments every time LiveFPL's backend re-aggregates; clients use it as a cache key."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "https://livefpl.us/version.json", false, []mcpParamBinding{}, []string{}),
	)
	// SQL tool — ad-hoc analysis on synced data without API calls
	s.AddTool(
		mcplib.NewTool("sql",
			mcplib.WithDescription("Run read-only SQL against local database. Use for ad-hoc analysis, aggregations, and joins across synced resources. Requires sync first."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("SQL query (SELECT or WITH...SELECT). Tables match resource names.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleSQL,
	)

	// Context tool — front-loaded domain knowledge for agents.
	// Call this first to understand the API taxonomy, query patterns, and capabilities.
	s.AddTool(
		mcplib.NewTool("context",
			mcplib.WithDescription("Get API domain context: resource taxonomy, auth requirements, query tips, and unique capabilities. Call this first."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleContext,
	)

	// Runtime Cobra-tree mirror — exposes every user-facing command that is
	// not already covered by a typed endpoint or framework MCP tool.
	cobratree.RegisterAll(s, cli.RootCmd(), cobratree.SiblingCLIPath)
}

type mcpParamBinding struct {
	PublicName string
	WireName   string
	Location   string
}

// makeAPIHandler creates a generic MCP tool handler for an API endpoint.
func makeAPIHandler(method, pathTemplate string, binaryResponse bool, bindings []mcpParamBinding, positionalParams []string) server.ToolHandlerFunc {
	return func(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
		c, err := newMCPClient()
		if err != nil {
			return mcplib.NewToolResultError(err.Error()), nil
		}

		// mcp-go v0.47+ made CallToolParams.Arguments an `any` to support
		// non-map payloads; GetArguments() returns the map[string]any shape
		// we rely on here (or an empty map when the payload is something else).
		args := req.GetArguments()

		// positionalParams mixes real URL path params with CLI positional
		// args that map to query params (e.g. `search <query>` -> ?query=);
		// the placeholder check below disambiguates them at runtime.
		path := pathTemplate
		knownArgs := make(map[string]bool, len(bindings))
		pathParams := make(map[string]bool, len(positionalParams))
		params := make(map[string]string)
		bodyArgs := make(map[string]any)
		var headers map[string]string
		if binaryResponse {
			headers = map[string]string{client.BinaryResponseHeader: "true"}
		}
		for _, binding := range bindings {
			knownArgs[binding.PublicName] = true
			v, ok := args[binding.PublicName]
			if !ok {
				continue
			}
			switch binding.Location {
			case "path":
				placeholder := "{" + binding.WireName + "}"
				pathParams[binding.PublicName] = true
				path = strings.Replace(path, placeholder, fmt.Sprintf("%v", v), 1)
			case "body":
				bodyArgs[binding.WireName] = v
			default:
				params[binding.WireName] = fmt.Sprintf("%v", v)
			}
		}
		for _, p := range positionalParams {
			placeholder := "{" + p + "}"
			if !strings.Contains(pathTemplate, placeholder) {
				continue
			}
			pathParams[p] = true
			if v, ok := args[p]; ok {
				path = strings.Replace(path, placeholder, fmt.Sprintf("%v", v), 1)
			}
		}

		for k, v := range args {
			if pathParams[k] || knownArgs[k] {
				continue
			}
			switch method {
			case "POST", "PUT", "PATCH":
				bodyArgs[k] = v
			default:
				params[k] = fmt.Sprintf("%v", v)
			}
		}

		var data json.RawMessage
		switch method {
		case "GET":
			if binaryResponse {
				data, err = c.GetWithHeaders(path, params, headers)
				break
			}
			data, err = c.Get(path, params)
		case "POST":
			if binaryResponse {
				data, _, err = c.PostWithParamsAndHeaders(path, params, bodyArgs, headers)
				break
			}
			data, _, err = c.PostWithParams(path, params, bodyArgs)
		case "PUT":
			if binaryResponse {
				data, _, err = c.PutWithParamsAndHeaders(path, params, bodyArgs, headers)
				break
			}
			data, _, err = c.PutWithParams(path, params, bodyArgs)
		case "PATCH":
			if binaryResponse {
				data, _, err = c.PatchWithParamsAndHeaders(path, params, bodyArgs, headers)
				break
			}
			data, _, err = c.PatchWithParams(path, params, bodyArgs)
		case "DELETE":
			if binaryResponse {
				data, _, err = c.DeleteWithParamsAndHeaders(path, params, headers)
				break
			}
			data, _, err = c.DeleteWithParams(path, params)
		default:
			return mcplib.NewToolResultError("unsupported method: " + method), nil
		}

		if err != nil {
			msg := err.Error()
			switch {
			case strings.Contains(msg, "HTTP 409"):
				return mcplib.NewToolResultText("already exists (no-op)"), nil
			case strings.Contains(msg, "HTTP 400") && cliutil.LooksLikeAuthError(msg):
				return mcplib.NewToolResultError("authentication error: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: the API rejected the request — this usually means auth is missing or invalid." +
					"\n      Set your API key: export FANTASY_PREMIER_LEAGUE_SESSION_COOKIE=<your-key>" +
					"\n      Run 'livefpl doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 401"):
				return mcplib.NewToolResultError("authentication failed: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: check your API key." +
					"\n      Set it with: export FANTASY_PREMIER_LEAGUE_SESSION_COOKIE=<your-key>" +
					"\n      Run 'livefpl doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 403"):
				return mcplib.NewToolResultError("permission denied: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: your credentials are valid but lack access to this resource." +
					"\n      Set it with: export FANTASY_PREMIER_LEAGUE_SESSION_COOKIE=<your-key>" +
					"\n      Run 'livefpl doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 404"):
				if method == "DELETE" {
					return mcplib.NewToolResultText("already deleted (no-op)"), nil
				}
				return mcplib.NewToolResultError("not found: " + msg), nil
			case strings.Contains(msg, "HTTP 429"):
				return mcplib.NewToolResultError("rate limited: " + msg), nil
			default:
				return mcplib.NewToolResultError(msg), nil
			}
		}

		// For GET responses, wrap bare arrays with count metadata
		if method == "GET" {
			trimmed := strings.TrimSpace(string(data))
			if len(trimmed) > 0 && trimmed[0] == '[' {
				var items []json.RawMessage
				if json.Unmarshal(data, &items) == nil {
					wrapped := map[string]any{
						"count": len(items),
						"items": items,
					}
					out, _ := json.Marshal(wrapped)
					return mcplib.NewToolResultText(string(out)), nil
				}
			}
		}
		if binaryResponse {
			out, _ := json.Marshal(map[string]any{
				"content_encoding": "base64",
				"data_base64":      base64.StdEncoding.EncodeToString(data),
				"byte_count":       len(data),
			})
			return mcplib.NewToolResultText(string(out)), nil
		}
		return mcplib.NewToolResultText(string(data)), nil
	}
}

func newMCPClient() (*client.Client, error) {
	home, _ := os.UserHomeDir()
	cfgPath := filepath.Join(home, ".config", "livefpl", "config.toml")
	cfg, err := config.Load(cfgPath)
	if err != nil {
		return nil, fmt.Errorf("loading config: %w", err)
	}
	c := client.New(cfg, 30*time.Second, 0)
	// Agents calling through MCP need fresh data every call. The on-disk
	// response cache survives across MCP server invocations, so a
	// DELETE/PATCH followed by a GET would otherwise return the
	// pre-mutation snapshot for up to the cache TTL. The interactive CLI
	// constructs its own client and is unaffected.
	c.NoCache = true
	return c, nil
}

func dbPath() string {
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".local", "share", "livefpl", "data.db")
}

// Note: MCP tools use their own dbPath() because they are in a separate package (main, not cli).
// The CLI's defaultDBPath() in the cli package uses the same canonical path.

// validateReadOnlyQuery gates the MCP sql tool. The agent contract advertised
// to the host is ReadOnlyHintAnnotation(true); a false annotation on a
// mutating tool lets MCP hosts auto-approve writes and is treated as a real
// bug per the project's agent-native security model.
//
// The gate is an allowlist (SELECT or WITH only) applied AFTER stripping the
// leading whitespace, line comments, block comments, and semicolons that
// SQLite itself ignores before parsing. A naive HasPrefix check on a
// keyword blocklist is bypassable by prefixing the dangerous statement with
// "/* x */" or "-- x\n" — TrimSpace strips outer whitespace but does not
// understand SQL comment syntax. Combined with the empirical fact that
// modernc.org/sqlite's mode=ro does NOT block VACUUM INTO (writes a snapshot
// to a new file) or ATTACH DATABASE (opens a separate writable handle),
// such a bypass produces silent exfiltration to an attacker-chosen path.
//
// SELECT and WITH are the only allowed leading keywords. WITH supports
// SELECT-form CTEs; CTE-wrapped writes ("WITH x AS (...) INSERT ...") are
// caught by OpenReadOnly's mode=ro one layer down. PRAGMA, ATTACH, VACUUM,
// and every other DDL/DML keyword fail at this gate before reaching SQLite.
func validateReadOnlyQuery(query string) error {
	upper := strings.ToUpper(stripLeadingSQLNoise(query))
	if !strings.HasPrefix(upper, "SELECT") && !strings.HasPrefix(upper, "WITH") {
		return fmt.Errorf("only SELECT queries are allowed")
	}
	return nil
}

// stripLeadingSQLNoise removes leading whitespace, SQL line comments
// (-- to end of line), block comments (/* ... */), and statement
// separators (;) from query. SQLite skips these before parsing the first
// keyword, so a security gate that does not strip them mismatches what the
// driver actually executes.
func stripLeadingSQLNoise(query string) string {
	for {
		query = strings.TrimLeft(query, " \t\r\n;")
		switch {
		case strings.HasPrefix(query, "--"):
			if idx := strings.IndexByte(query, '\n'); idx >= 0 {
				query = query[idx+1:]
				continue
			}
			return ""
		case strings.HasPrefix(query, "/*"):
			if idx := strings.Index(query[2:], "*/"); idx >= 0 {
				query = query[2+idx+2:]
				continue
			}
			return ""
		default:
			return query
		}
	}
}

func handleSQL(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	query, ok := args["query"].(string)
	if !ok || query == "" {
		return mcplib.NewToolResultError("query is required"), nil
	}

	if err := validateReadOnlyQuery(query); err != nil {
		return mcplib.NewToolResultError(err.Error()), nil
	}

	db, err := store.OpenReadOnly(dbPath())
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("opening database: %v", err)), nil
	}
	defer db.Close()

	rows, err := db.Query(query)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("query failed: %v", err)), nil
	}
	defer rows.Close()

	cols, _ := rows.Columns()
	var results []map[string]any
	for rows.Next() {
		values := make([]any, len(cols))
		ptrs := make([]any, len(cols))
		for i := range values {
			ptrs[i] = &values[i]
		}
		rows.Scan(ptrs...)
		row := make(map[string]any)
		for i, col := range cols {
			row[col] = values[i]
		}
		results = append(results, row)
	}

	data, _ := json.MarshalIndent(results, "", "  ")
	return mcplib.NewToolResultText(string(data)), nil
}

func handleContext(_ context.Context, _ mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	ctx := map[string]any{
		"api":         "livefpl",
		"description": "Combined CLI for multiple API services",
		"archetype":   "payments",
		"tool_count":  23,
		// tool_surface tells agents which surface a capability lives on.
		"tool_surface": "MCP exposes typed endpoint tools plus a runtime mirror of user-facing CLI commands. Endpoint tools keep typed schemas; command-mirror tools shell out to the companion livefpl binary.",
		"auth": map[string]any{
			"type":     "api_key",
			"env_vars": []map[string]any{},
		},
		"resources": []map[string]any{
			{
				"name":        "bootstrap-static",
				"description": "Manage bootstrap static",
				"endpoints":   []string{"get"},
			},
			{
				"name":        "dream-team",
				"description": "Manage dream team",
				"endpoints":   []string{"get"},
			},
			{
				"name":        "element-summary",
				"description": "Manage element summary",
				"endpoints":   []string{"get"},
			},
			{
				"name":        "elite-json",
				"description": "Manage elite json",
				"endpoints":   []string{"get-elite-aggregates"},
			},
			{
				"name":        "entry",
				"description": "Manage entry",
				"endpoints":   []string{"get"},
			},
			{
				"name":        "event",
				"description": "Manage event",
				"endpoints":   []string{},
			},
			{
				"name":        "event-status",
				"description": "Manage event status",
				"endpoints":   []string{"get"},
			},
			{
				"name":        "fixtures",
				"description": "Manage fixtures",
				"endpoints":   []string{"get"},
			},
			{
				"name":        "games-json",
				"description": "Manage games json",
				"endpoints":   []string{"get-live-games"},
				"searchable":  true,
			},
			{
				"name":        "leagues-classic",
				"description": "Manage leagues classic",
				"endpoints":   []string{},
			},
			{
				"name":        "leagues-h2h-matches",
				"description": "Manage leagues h2h matches",
				"endpoints":   []string{"get-h2h-league-matches"},
			},
			{
				"name":        "lh-api2",
				"description": "Manage lh api2",
				"endpoints":   []string{"get-planner-snapshot"},
			},
			{
				"name":        "livefplapi",
				"description": "Manage livefplapi",
				"endpoints":   []string{"get-live-team"},
			},
			{
				"name":        "locals-league-id-json",
				"description": "Manage locals league id json",
				"endpoints":   []string{"get-league-locals-snapshot"},
			},
			{
				"name":        "me",
				"description": "Manage me",
				"endpoints":   []string{"get"},
			},
			{
				"name":        "my-team",
				"description": "Manage my team",
				"endpoints":   []string{"get"},
			},
			{
				"name":        "prices-json",
				"description": "Manage prices json",
				"endpoints":   []string{"get-prices"},
			},
			{
				"name":        "team",
				"description": "Manage team",
				"endpoints":   []string{"get-set-piece-notes"},
			},
			{
				"name":        "top-transfers-json",
				"description": "Manage top transfers json",
				"endpoints":   []string{"get-top-transfers"},
			},
			{
				"name":        "version-json",
				"description": "Manage version json",
				"endpoints":   []string{"get-version"},
			},
		},
		"query_tips": []string{
			"Pagination uses cursor-based paging. Pass after parameter for subsequent pages.",
			"Control page size with the limit parameter (default 100).",
			"Use the sql tool for ad-hoc analysis on synced data. Run sync first to populate the local database.",
			"Use the search tool for full-text search across all synced resources. Faster than iterating list endpoints.",
			"Prefer sql/search over repeated API calls when the data is already synced.",
		},
		"playbook": []map[string]string{
			{"topic": "Financial data", "insight": "Always use read-only operations for financial queries. Never use create/update tools for payment data without explicit user confirmation."},
			{"topic": "Reconciliation", "insight": "For reconciliation tasks, sync first then use sql for cross-referencing. API pagination over financial records is slow and rate-limited."},
		},
	}
	data, _ := json.MarshalIndent(ctx, "", "  ")
	return mcplib.NewToolResultText(string(data)), nil
}

// RegisterNovelFeatureTools is kept as a compatibility no-op for older MCP
// mains. New generated mains call RegisterTools only; RegisterTools now
// includes the runtime Cobra-tree mirror.
func RegisterNovelFeatureTools(s *server.MCPServer) {
	_ = s
}
