// Copyright 2026 ananth-menon. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newEventLiveCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "live",
		Short: "Manage live",
		RunE:  parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newEventLiveGetEventCmd(flags))
	return cmd
}
